package com.niit.Gadgets.model;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

//replica of table
//it has to pass atributes(variables)  to DAO
//it is used to represent table name

@Entity
@Table(name="product")
@Component 
public class Product 
{
 //refers to primary key automatically

  
  //here Id we are not taking from user so it should be autogenerated.
	@Id
    private String p_id; 
	private String p_name;
	private int p_price;
	private String p_description;
	private String categoryId;
	private String suppId;
	
	  @ManyToOne
	  @JoinColumn(name="categoryId",nullable=false,updatable=false,insertable=false)
	  private Category  category;
	  
	  @ManyToOne
	  @JoinColumn(name="suppId",nullable=false,updatable=false,insertable=false)
	  private Supplier supplier;
	
	  
  public String getp_id() {
	return p_id;
}

public void setp_id(String p_id) {
	this.p_id =  p_id;
}

public String getp_name() {
	return p_name;
}

public void setp_name(String p_name) {
	this.p_name = p_name;
}

public int getp_price() {
	return p_price;
}

public void setp_price(int p_price) {
	this.p_price = p_price;
}

public String getp_description() {
	return p_description;
}

public void setp_description(String p_description) {
	this.p_description = p_description;
}


 
  
public Category getCategory() {
	return category;
}

public void setCategory(Category category) {
	this.category = category;
}

public Supplier getSupplier() {
	return supplier;
}

public void setSupplier(Supplier supplier) {
	this.supplier = supplier;
}

public String getCategoryId() {
	return categoryId;
}

public void setCategoryId(String categoryId) {
	this.categoryId = categoryId;
}

public String getSuppId() {
	return suppId;
}

public void setSuppId(String suppId) {
	this.suppId= suppId;
}
  
  @Transient
  private MultipartFile image;
  
  
  public MultipartFile getImage()
  {
	  return image;
  }
  
  public void setImage(MultipartFile image)
  {
	  this.image=image;
  }
  
    
}
